### ISSUE TITLE
Kotlin 2.1.21 Version, composeInstrumentation "InstrumentationMode.AUTO" Build Problems

### ISSUE THREAD

**Issue by Asinab** [DataDog/dd-sdk-android-gradle-plugin#419]
### Question

Hello,

I'm using Kotlin version 2.1.21. During the build process, I'm encountering the error below. Without downgrading the Kotlin version, how can I use `InstrumentationMode.AUTO` in `composeInstrumentation`?

```
kotlin:2.1.21
ksp:2.1.21-2.0.1
composeBom :"2025.07.00"
datadoghq:2.25.0
```

Error Log

```
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.ir.expressions.IrCall org.jetbrains.kotlin.ir.builders.ExpressionHelpersKt.irCall$default(org.jetbrains.kotlin.ir.builders.IrBuilderWithScope, org.jetbrains.kotlin.ir.symbols.IrSimpleFunctionSymbol, org.jetbrains.kotlin.ir.types.IrType, int, int, org.jetbrains.kotlin.ir.expressions.IrStatementOrigin, int, java.lang.Object)'
	at com.datadog.gradle.plugin.kcp.ComposeTagTransformer.buildDatadogTagModifierCall(ComposeTagTransformer.kt:183)
	at com.datadog.gradle.plugin.kcp.ComposeTagTransformer.buildIrExpression(ComposeTagTransformer.kt:147)
	at com.datadog.gradle.plugin.kcp.ComposeTagTransformer.visitCall(ComposeTagTransformer.kt:107)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:305)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:24)
```

**Comment by ambushwork** [comment]
Hello @Asinab  we just released a new version [1.19.0](https://github.com/DataDog/dd-sdk-android-gradle-plugin/releases/tag/1.19.0) which should resolve the issue you reported. Please let us know if you encounter any further problems with this release.

**Comment by ambushwork** [comment]
@nazim-karos thanks for the report, we are working on the support for kotlin 2.2.20

**Comment by ambushwork** [comment]
@nazim-karos @ilkersi We just released the [new version 1.21.0](https://github.com/DataDog/dd-sdk-android-gradle-plugin/releases/tag/1.21.0) with the support of Kotlin 2.2.20, it should fix the issue. You are welcome to come back to us if you've seen some other issue

**Comment by ilkersi** [comment]
Hi @ambushwork , thank you for the quick fix. I confirm that now it works with the following versions:
```
kotlin = "2.2.20"
ksp = "2.2.20-2.0.3"
composeBom :"2025.02.00"
datadog = "2.25.0"
datadogPlugin = "1.21.0"
```
